.Dd October 12, 2011
.Dt PAM_USBKEY 8
.Os
.Sh NAME
.Nm pam_usbkey
.Nd uwierzytelnianie na podstawie obecności kluczy USB
.Sh DESCRIPTION
Zadaniem modułu
.Nm pam_usbkey
jest umożliwienie uwierzytelniania na podstawie obecności w systemie kluczy USB
o unikalnym numerze seryjnym.
.Sh EXAMPLES
Wymuszenie użycia modułu
.Nm
jako wystarczającego do pomyślnego zakończenia procesu logowania wymaga
modyfikacji pliku
.Pa /etc/pam.d/login
poprzez dodanie na szczycie stosu modułów linii:
.Pp
.Dl "auth      sufficient      pam_usbkey.so"
.Pp
Po dokonaniu powyższej zmiany obecność urządzenia o numerze seryjnym
przyporządkowanym do danego użytkownika eliminuje konieczność podawania
przez niego hasła w procesie logowania.
.Pp
Inną możliwością jest wykorzystanie modułu
.Nm
razem ze standardową metodą uwierzytelniania hasłem, zaimplementowaną w postaci
modułu
.Xr pam_unix 8 .
W tym wypadku proces logowania kończy się sukcesem jedynie w sytuacji, gdy
obydwa moduły zakończą działanie z pozytywnym rezultatem.
Narzuca to konieczność uzupełnienia pliku
.Pa /etc/pam.d/login
o linie:
.Pp
.Dl "auth      required        pam_usbkey.so"
.Dl "auth      required        pam_unix.so"
.Pp
Jeżeli moduł znajduje się w innej lokalizacji niż
.Pa /usr/lib/
konieczne jest podanie ścieżki absolutnej.
.Sh NOTES
Plik konfiguracyjny modułu przechowywany jest w katalogu
.Pa /etc/security/
pod nazwą
.Sy usbkey.conf .
Stanowi on przyporządkowanie numerów seryjnych urządzeń USB użytkownikom
systemu.
Każda linia pliku składa się z pary
.Li nazwa_użytkownika:numer_seryjny .
.Sh AUTHORS
.An Bartosz Pieńkowski Aq pienkowb@iem.pw.edu.pl
.Sh FILES
.Bl -item -compact
.It
.Pa /etc/security/usbkey.conf
.It
.Pa /etc/pam.d/login
.It
.Pa /etc/pam.d/sshd
.El
.Sh SEE ALSO
.Xr usbserial 1 ,
.Xr pam 3 ,
.Xr pam_unix 8
