.Dd October 12, 2011
.Dt USBSERIAL 1
.Os
.Sh NAME
.Nm usbserial
.Nd odczytuje numer seryjny urządzenia USB
.Sh SYNOPSIS
.Nm Ar bus_number device_address
.Sh DESCRIPTION
.Sh EXAMPLES
.Sh NOTES
.Sh AUTHORS
.An Bartosz Pieńkowski Aq pienkowb@iem.pw.edu.pl
.Sh FILES
.Pa /etc/security/usbkey.conf
.Sh SEE ALSO
.Xr usbconfig 1 ,
.Xr pam_usbkey 8
