.Dd October 12, 2011
.Dt USBSERIAL 1
.Os
.Sh NAME
.Nm usbserial
.Nd odczytuje numer seryjny urządzenia USB
.Sh SYNOPSIS
.Nm Ar bus_number device_address
.Sh DESCRIPTION
Program
.Nm
odczytuje i wyświetla numer seryjny przypisany do urządzenia USB o adresie
.Ar device_address ,
zlokalizowanego na szynie
.Ar bus_number .
.Pp
Wywołanie programu kończy się niepowodzeniem w przypadku podania błędnej
lokalizacji urządzenia, jak również z powodu braku przypisanego numeru
seryjnego.
.Sh EXAMPLES
Przyczyną powstania programu
.Nm
była potrzeba usprawnienia procesu konfiguracji modułu
.Xr pam_usbkey 8 .
Przykładowo wydanie polecenia:
.Pp
.Dl echo `id -u -n`:`usbserial 0 1` >> /etc/security/usbkey.conf
.Pp
umożliwi zalogowanemu użytkownikowi uwierzytelnianie przy pomocy urządzenia
podłączonego w momencie wydawania komendy do szyny
.Li 0
pod adresem
.Li 1 .
.Sh NOTES
W celu uzyskania numeru szyny i adresu urządzenia można wykorzystać program
.Xr usbconfig 8 .
.Pp
Do prawidłowego działania programu
.Nm
wymagane są prawa administratora systemu.
.Sh AUTHORS
.An Bartosz Pieńkowski Aq pienkowb@iem.pw.edu.pl
.Sh FILES
.Pa /etc/security/usbkey.conf
.Sh SEE ALSO
.Xr pam_usbkey 8 ,
.Xr usbconfig 8
