.Dd October 12, 2011
.Dt USBSERIAL 1
.Os
.Sh NAME
.Nm usbserial
.Nd odczytuje numer seryjny urządzenia USB
.Sh SYNOPSIS
.Nm Ar bus_number device_address
.Sh DESCRIPTION
Program
.Nm
odczytuje i wyświetla numer seryjny przypisany do urządzenia USB o adresie
.Ar device_address ,
zlokalizowanego na szynie
.Ar bus_number .
.Pp
Wywołanie programu kończy się niepowodzeniem w przypadku podania błędnej
lokalizacji urządzenia, jak również z powodu braku przypisanego numeru
seryjnego.
.Sh EXAMPLES
.Sh NOTES
W celu uzyskania numeru szyny i adresu urządzenia można wykorzystać program
.Xr usbconfig 1 .
.Pp
Do prawidłowego działania programu
.Nm
wymagane są prawa administratora systemu.
.Sh AUTHORS
.An Bartosz Pieńkowski Aq pienkowb@iem.pw.edu.pl
.Sh FILES
.Pa /etc/security/usbkey.conf
.Sh SEE ALSO
.Xr usbconfig 1 ,
.Xr pam_usbkey 8
